-- ============================================================
-- SEED: Masukkan buku-buku statis ke database Supabase
-- Jalankan di Supabase SQL Editor
-- ============================================================

-- Hapus data lama (opsional, hati-hati jika ada data baru dari admin)
-- DELETE FROM public.chapters WHERE book_id IN ('1','2','3','4','5','6','7','8','9','10','11','12');
-- DELETE FROM public.books WHERE id IN ('1','2','3','4','5','6','7','8','9','10','11','12');

INSERT INTO public.books (id, title, author, cover_url, price, old_price, rating, review_count, badge, genre, pages, publisher, publish_year, description, is_premium, is_active) VALUES
('1', 'Atomic Habits', 'James Clear', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500', 79000, 99000, 4.9, 1284, 'Best Seller', 'Self Improvement', 320, 'Gramedia', 2020, 'Atomic Habits menawarkan kerangka kerja yang telah terbukti untuk memperbaiki setiap hari. James Clear, salah satu penulis terkemuka di dunia dalam hal pembentukan kebiasaan, mengungkapkan strategi-strategi praktis yang akan mengajarkan Anda cara membentuk kebiasaan baik, menghilangkan yang buruk, dan menguasai perilaku-perilaku kecil yang menghasilkan hasil luar biasa.', false, true),
('2', 'Filosofi Teras', 'Henry Manampiring', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500', 85000, NULL, 4.8, 987, 'Populer', 'Self Improvement', 288, 'Kompas', 2019, 'Filosofi Teras membahas filsafat Stoa dari sudut pandang yang relevan dengan kehidupan modern Indonesia. Buku ini mengajak pembaca untuk menemukan ketenangan dan kebahagiaan sejati di tengah dunia yang penuh tekanan.', false, true),
('3', 'Deep Work', 'Cal Newport', 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500', 72000, NULL, 4.9, 756, NULL, 'Bisnis', 304, 'Grand Central Publishing', 2016, 'Deep Work adalah kemampuan untuk fokus tanpa gangguan pada tugas yang menuntut kognitif. Buku ini menunjukkan mengapa kemampuan ini semakin langka dan semakin berharga di dunia saat ini.', false, true),
('4', 'Psychology of Money', 'Morgan Housel', 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500', 91000, NULL, 5.0, 1102, 'Editor''s Pick', 'Bisnis', 268, 'Harriman House', 2020, 'Buku ini mengungkapkan cara orang berpikir tentang uang dan cara mengubah pola pikir itu untuk membuat keputusan keuangan yang lebih baik.', false, true),
('5', 'Ikigai', 'Hector Garcia', 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=500', 82000, NULL, 4.8, 843, NULL, 'Self Improvement', 208, 'Penguin Books', 2017, 'Ikigai adalah kata Jepang yang berarti alasan untuk hidup. Buku ini menjelajahi rahasia kebahagiaan dan umur panjang orang-orang di Okinawa, Jepang.', false, true),
('6', 'Bumi', 'Tere Liye', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500', 69000, NULL, 4.7, 654, NULL, 'Fantasi', 440, 'Gramedia', 2014, 'Raib, gadis 15 tahun yang bisa menghilang, suatu hari menemukan pintu menuju dunia lain dengan peradaban yang jauh lebih maju.', false, true),
('7', 'Laut Bercerita', 'Leila S. Chudori', 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=500', 91000, NULL, 5.0, 921, 'Editor''s Pick', 'Novel', 384, 'KPG', 2017, 'Novel tentang mahasiswa aktivis yang hilang di era Orde Baru, diceritakan dari dua sudut pandang: Biru Laut yang hilang, dan adiknya Asmara Jati yang terus mencari.', false, true),
('8', 'Sapiens', 'Yuval Noah Harari', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500', 105000, NULL, 5.0, 1589, 'Best Seller', 'Sejarah', 512, 'Harper', 2011, 'Dari manusia purba hingga era teknologi modern, Sapiens mengajak kita menelusuri perjalanan luar biasa umat manusia.', true, true),
('9', 'The Mountain Is You', 'Brianna Wiest', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500', 95000, NULL, 5.0, 778, 'New', 'Self Improvement', 248, 'Thought Catalog Books', 2020, 'Buku transformatif tentang cara mengatasi hambatan diri sendiri.', false, true),
('10', 'Start With Why', 'Simon Sinek', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500', 89000, NULL, 4.8, 1034, NULL, 'Bisnis', 256, 'Portfolio', 2009, 'Simon Sinek mengungkap pola pikir yang membedakan pemimpin dan organisasi yang menginspirasi dari yang lainnya.', false, true),
('11', 'Rich Dad Poor Dad', 'Robert T. Kiyosaki', 'https://images.unsplash.com/photo-1543286386-2e659306cd6c?w=500', 74000, NULL, 4.8, 2001, 'Best Seller', 'Bisnis', 336, 'Warner Books', 1997, 'Robert Kiyosaki berbagi pelajaran keuangan yang ia pelajari dari dua ayah.', false, true),
('12', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500', 99000, NULL, 4.9, 1356, NULL, 'Teknologi', 499, 'Farrar, Straus and Giroux', 2011, 'Daniel Kahneman mengungkapkan dua sistem berpikir manusia dan bagaimana keduanya mempengaruhi setiap keputusan kita.', true, true)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, author = EXCLUDED.author, cover_url = EXCLUDED.cover_url,
  price = EXCLUDED.price, old_price = EXCLUDED.old_price, rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count, badge = EXCLUDED.badge, genre = EXCLUDED.genre,
  pages = EXCLUDED.pages, publisher = EXCLUDED.publisher, publish_year = EXCLUDED.publish_year,
  description = EXCLUDED.description, is_premium = EXCLUDED.is_premium;

-- Chapters untuk semua buku
INSERT INTO public.chapters (book_id, title, content, order_num, is_free) VALUES
-- Atomic Habits
('1', 'Bab 1 — Kekuatan Kebiasaan Kecil', 'Kebiasaan kecil yang dilakukan secara konsisten akan menghasilkan perubahan besar. James Clear menjelaskan bagaimana 1% perbaikan setiap hari dapat menghasilkan hasil yang luar biasa dalam jangka panjang. Bayangkan jika Anda bisa menjadi 1% lebih baik setiap hari selama setahun - Anda akan 37 kali lebih baik pada akhir tahun itu. Sebaliknya, jika Anda 1% lebih buruk setiap hari selama setahun, Anda akan menurun hampir ke nol.', 1, true),
('1', 'Bab 2 — Identitas & Kebiasaan', 'Perubahan sejati dimulai dari identitas, bukan dari hasil yang diinginkan. Kebanyakan orang memulai dengan memikirkan hasil (saya ingin kurus), kemudian proses (diet dan olahraga ini), dan identitas (saya yang baru). Clear menyarankan urutan terbalik: mulailah dengan identitas siapa yang ingin Anda jadikan.', 2, false),
('1', 'Bab 3 — Cara Membangun Kebiasaan Baru', 'Empat langkah untuk membangun kebiasaan: Isyarat (Cue), Keinginan (Craving), Respons (Response), dan Hadiah (Reward). Setiap kebiasaan dimulai dengan isyarat yang memicu otak untuk memulai perilaku, karena isyarat itu memprediksi hadiah. Keinginan adalah kekuatan motivasi di balik setiap kebiasaan.', 3, false),
('1', 'Bab 4 — Hukum Pertama: Buat Tampak Jelas', 'Hukum pertama perubahan perilaku adalah membuat isyarat kebiasaan baik Anda tampak jelas dan terlihat. Jika Anda ingin membangun kebiasaan, Anda perlu membuatnya lebih mudah dilakukan. Jika Anda ingin menghentikan kebiasaan buruk, Anda perlu membuatnya lebih tidak terlihat.', 4, false),
('1', 'Bab 5 — Hukum Kedua: Buat Menarik', 'Semakin menarik sebuah kesempatan, semakin besar kemungkinan membentuk suatu kebiasaan. Anda dapat membuat kebiasaan baik lebih menarik dengan menggunakan strategi penumpukan kebiasaan, di mana Anda menggabungkan tindakan yang perlu Anda lakukan dengan tindakan yang ingin Anda lakukan.', 5, false),
-- Filosofi Teras
('2', 'Bab 1 — Apa Itu Stoisisme?', 'Stoisisme adalah mazhab filsafat Yunani yang didirikan sekitar tahun 300 SM oleh Zeno dari Citium. Stoisisme mengajarkan bahwa kebajikan, yang didasarkan pada pengetahuan, adalah satu-satunya kebaikan sejati. Buku ini menjelaskan bagaimana prinsip-prinsip Stoa bisa diterapkan dalam kehidupan modern Indonesia.', 1, true),
('2', 'Bab 2 — Dikotomi Kendali', 'Prinsip inti Stoisisme adalah membedakan apa yang ada dalam kendali kita dan apa yang tidak. Pikiran, perasaan, dan tindakan kita berada dalam kendali kita. Kejadian eksternal tidak. Dengan fokus hanya pada apa yang bisa kita kendalikan, kita bisa menemukan kedamaian sejati.', 2, false),
('2', 'Bab 3 — Emosi Negatif', 'Stoisisme mengajarkan bahwa emosi negatif seperti kecemasan, kemarahan, dan kesedihan bukanlah akibat dari peristiwa yang menimpa kita, melainkan akibat dari cara kita menilai peristiwa tersebut. Dengan mengubah penilaian kita, kita bisa mengubah emosi kita.', 3, false),
('2', 'Bab 4 — Membangun Resiliensi', 'Resiliensi adalah kemampuan untuk bangkit dari kegagalan dan tantangan. Stoisisme menawarkan praktik konkret untuk membangun resiliensi: visualisasi negatif, memfokuskan perhatian pada momen sekarang, dan memandang setiap rintangan sebagai peluang untuk berkembang.', 4, false),
-- Deep Work
('3', 'Bab 1 — Deep Work Bernilai', 'Deep Work, atau kerja mendalam, adalah kemampuan untuk fokus tanpa gangguan pada tugas yang menuntut kognitif. Kemampuan ini menghasilkan nilai luar biasa di ekonomi saat ini, karena menciptakan produk yang sulit ditiru dan mendorong Anda ke batas kemampuan kognitif Anda.', 1, true),
('3', 'Bab 2 — Deep Work Langka', 'Ironisnya, meskipun Deep Work semakin berharga, Deep Work semakin jarang dilakukan. Budaya bisnis yang mendominasi - email, media sosial, pertemuan terus-menerus - secara aktif menghancurkan kemampuan untuk fokus mendalam.', 2, false),
('3', 'Bab 3 — Deep Work Bermakna', 'Selain bernilai secara ekonomi, Deep Work juga bermakna secara psikologis. Penelitian menunjukkan bahwa kondisi flow - keadaan keterlibatan penuh dan fokus mendalam - adalah salah satu sumber utama kebahagiaan yang dilaporkan oleh manusia.', 3, false),
('3', 'Bab 4 — Aturan 1: Bekerja Dalam-Dalam', 'Untuk melakukan Deep Work secara konsisten, Anda memerlukan ritual dan strategi. Newport membahas berbagai filosofi Deep Work: monastik (menghilangkan semua gangguan), bimodal (bergantian antara mode mendalam dan dangkal), ritmis (jadwal harian yang konsisten), dan jurnalistik.', 4, false),
-- Psychology of Money
('4', 'Bab 1 — Tidak Ada yang Gila', 'Orang membuat keputusan keuangan yang aneh bukan karena mereka bodoh, tetapi karena mereka memiliki pengalaman berbeda yang membentuk perspektif berbeda tentang uang. Seorang yang tumbuh dalam kemiskinan dan seseorang yang lahir dalam kemewahan akan memiliki pandangan sangat berbeda tentang risiko dan nilai.', 1, true),
('4', 'Bab 2 — Keberuntungan & Risiko', 'Keberuntungan dan risiko adalah saudara kandung. Keduanya adalah kenyataan bahwa setiap hasil dalam kehidupan adalah dipandu oleh kekuatan selain usaha individu. Housel mengingatkan kita untuk tidak terlalu mengagungkan kesuksesan orang lain atau terlalu menyalahkan kegagalan orang lain, karena nasib memainkan peran yang lebih besar dari yang kita akui.', 2, false),
('4', 'Bab 3 — Tidak Pernah Cukup', 'Kemampuan untuk mengatakan "cukup" adalah salah satu keterampilan keuangan yang paling berharga, tetapi jarang dibicarakan. Banyak orang kaya yang menghancurkan karir dan reputasi mereka karena ketidakmampuan mengatakan cukup.', 3, false),
('4', 'Bab 4 — Membungakan Waktu', 'Warren Buffett memiliki kekayaan sekitar $84 miliar. Darinya, $81 miliar diperoleh setelah ulang tahun ke-65. Rahasia sebenarnya dari kekayaan Buffett bukan hanya tentang investasi yang baik, tetapi tentang investasi yang baik selama 70 tahun. Ini adalah kekuatan bunga berbunga.', 4, false),
-- Ikigai
('5', 'Bab 1 — Ikigai, Seni Tetap Muda', 'Orang-orang di Okinawa, Jepang, memiliki usia harapan hidup tertinggi di dunia. Salah satu rahasianya adalah ikigai - alasan untuk bangun di pagi hari. Ikigai adalah persimpangan antara apa yang Anda cintai, apa yang Anda kuasai, apa yang dunia butuhkan, dan apa yang bisa menghasilkan uang bagi Anda.', 1, true),
('5', 'Bab 2 — Anti-Penuaan', 'Penelitian menunjukkan bahwa tetap aktif secara mental dan fisik, memiliki tujuan hidup, dan mempertahankan koneksi sosial adalah kunci untuk menua dengan anggun. Orang-orang di Okinawa jarang pensiun sepenuhnya; mereka terus bergerak dan berkontribusi sesuai kemampuan.', 2, false),
('5', 'Bab 3 — Flow', 'Flow adalah keadaan di mana Anda begitu tenggelam dalam suatu aktivitas sehingga Anda kehilangan jejak waktu. Ini adalah kondisi ideal antara bosan dan cemas - ketika tantangan sesuai dengan kemampuan Anda. Menemukan aktivitas yang mendatangkan flow adalah bagian penting dari menemukan ikigai.', 3, false),
-- Bumi
('6', 'Bab 1 — Raib yang Bisa Menghilang', 'Raib adalah gadis SMP yang tampak biasa, kecuali satu hal: dia bisa menghilang. Kemampuan itu dimilikinya sejak kecil, tetapi dia tidak pernah memahami asal-usulnya. Suatu hari, petualangan yang tidak terduga mengubah hidupnya selamanya.', 1, true),
('6', 'Bab 2 — Pintu Rahasia', 'Di balik lemari tua di kamarnya, Raib menemukan pintu yang membawanya ke dunia lain. Dunia yang indah namun berbahaya, dengan teknologi yang jauh melampaui Bumi, tetapi juga dengan ancaman yang mengintai dari bayangan.', 2, false),
('6', 'Bab 3 — Dunia Bawah Tanah', 'Bersama dua sahabat setianya, Raib menjelajahi dunia bawah tanah yang menakjubkan. Mereka menemukan bahwa kemampuan Raib bukan kebetulan - ada warisan dan takdir yang menunggunya.', 3, false),
-- Laut Bercerita
('7', 'Bab 1 — Biru Laut', 'Biru Laut adalah mahasiswa aktivis tahun 1990-an yang berjuang melawan penindasan. Kisahnya dimulai dari momen-momen sebelum penghilangannya, memperlihatkan keberanian, cinta, dan keyakinan seorang pemuda yang percaya perubahan adalah mungkin.', 1, true),
('7', 'Bab 2 — Asmara Jati', 'Asmara Jati, adik Biru Laut, hidup dalam duka dan ketidakpastian setelah kakaknya menghilang. Bertahun-tahun kemudian, dia masih mencari kebenaran tentang apa yang terjadi pada saudaranya.', 2, false),
('7', 'Bab 3 — 1998', 'Reformasi 1998 menjadi latar belakang kisah ini - masa di mana banyak mahasiswa hilang tanpa jejak. Leila S. Chudori dengan indah menggambarkan bagaimana sejarah meninggalkan luka yang tak pernah sembuh pada mereka yang ditinggalkan.', 3, false),
-- Sapiens
('8', 'Bab 1 — Binatang yang Tidak Penting', 'Sekitar 13,5 miliar tahun yang lalu, materi, energi, waktu, dan ruang muncul dalam apa yang dikenal sebagai Big Bang. Tiga ratus ribu tahun kemudian, materi dan energi mulai bergumpal menjadi struktur kompleks yang disebut atom. Dari sana, evolusi berlanjut hingga munculnya Homo sapiens - binatang yang paling tidak penting, hingga tiba-tiba menjadi penguasa planet.', 1, true),
('8', 'Bab 2 — Pohon Pengetahuan', 'Revolusi Kognitif terjadi sekitar 70.000 tahun yang lalu dan merupakan titik balik terbesar dalam sejarah manusia. Tiba-tiba, Homo sapiens mampu berpikir dan berkomunikasi dengan cara yang sama sekali baru, memungkinkan mereka untuk membangun jaringan sosial yang lebih kompleks dari spesies lain.', 2, false),
-- The Mountain Is You
('9', 'Bab 1 — Mengapa Kita Menyabotase Diri', 'Sabotase diri adalah cara kita melindungi diri dari sesuatu yang kita percaya tidak bisa kita tangani. Perilaku yang tampak merusak seringkali adalah upaya untuk menghindari emosi yang lebih menyakitkan - rasa takut akan kegagalan, penolakan, atau pengulangan pola lama.', 1, true),
('9', 'Bab 2 — Kebiasaan Merusak', 'Kebiasaan merusak adalah respons terhadap emosi yang tidak terproses. Sebelum Anda bisa mengubah perilaku, Anda harus memahami apa yang mendasarinya. Setiap kebiasaan buruk adalah petunjuk tentang kebutuhan yang belum terpenuhi.', 2, false),
('9', 'Bab 3 — Membangun Diri Baru', 'Membangun diri baru dimulai dengan pertanyaan sederhana: siapa yang ingin saya jadikan? Bukan apa yang ingin saya capai, tetapi siapa yang ingin saya jadikan. Identitas menentukan tindakan, bukan sebaliknya.', 3, false),
-- Start With Why
('10', 'Bab 1 — Asumsikan Anda Tahu', 'Manipulasi versus inspirasi: ada dua cara untuk mempengaruhi perilaku manusia - manipulasi dan inspirasi. Pemimpin dan organisasi yang paling sukses bukan yang terbaik dalam apa yang mereka lakukan, tetapi yang paling jelas tentang mengapa mereka melakukannya.', 1, true),
('10', 'Bab 2 — Golden Circle', 'Golden Circle adalah tiga lingkaran konsentris: Mengapa (inti), Bagaimana (tengah), dan Apa (luar). Semua orang tahu APA yang mereka lakukan. Beberapa tahu BAGAIMANA. Sangat sedikit yang tahu MENGAPA. Pemimpin yang menginspirasi berpikir, bertindak, dan berkomunikasi dari dalam ke luar.', 2, false),
('10', 'Bab 3 — Pemimpin yang Menginspirasi', 'Apple, Martin Luther King, dan Wright Brothers memiliki satu kesamaan: mereka dimulai dengan MENGAPA. Mereka tidak menjual apa yang mereka buat; mereka menjual mengapa mereka membuatnya. Dan itulah yang menciptakan pengikut yang loyal, bukan sekadar pelanggan.', 3, false),
-- Rich Dad Poor Dad
('11', 'Bab 1 — Rich Dad, Poor Dad', 'Robert Kiyosaki memiliki dua ayah - ayah kandungnya yang berpendidikan tinggi namun selalu berjuang secara finansial, dan ayah teman sekolahnya yang putus sekolah namun menjadi salah satu orang terkaya di Hawaii. Dua pria ini memberinya sudut pandang yang sangat berbeda tentang uang.', 1, true),
('11', 'Bab 2 — Orang Kaya Tidak Bekerja untuk Uang', 'Orang miskin dan kelas menengah bekerja untuk uang. Orang kaya membuat uang bekerja untuk mereka. Perbedaan utama bukan pada pendapatan, tetapi pada bagaimana mereka berpikir tentang dan menggunakan uang.', 2, false),
('11', 'Bab 3 — Melek Finansial', 'Kecerdasan finansial adalah fondasi dari kekayaan sejati. Ini melibatkan pemahaman akuntansi dasar, investasi, hukum pajak, dan dinamika pasar. Sekolah tidak mengajarkan ini, itulah mengapa banyak orang berpenghasilan tinggi tetapi tetap miskin.', 3, false),
-- Thinking, Fast and Slow
('12', 'Bab 1 — Karakter Cerita', 'Kahneman memperkenalkan dua sistem berpikir: Sistem 1 yang cepat, intuitif, dan emosional; dan Sistem 2 yang lambat, deliberatif, dan logis. Sebagian besar pemikiran kita dikendalikan oleh Sistem 1, yang efisien tetapi rentan terhadap bias.', 1, true),
('12', 'Bab 2 — Perhatian dan Usaha', 'Sistem 2 membutuhkan perhatian dan usaha. Ketika kita fokus pada tugas yang sulit, kita menggunakan sumber daya kognitif yang terbatas. Inilah mengapa pengambilan keputusan yang sulit sangat melelahkan.', 2, false),
('12', 'Bab 3 — Mesin Lompatan Kesimpulan', 'Sistem 1 mahir membuat narasi kohesif dari informasi yang terbatas. Ini berguna untuk keputusan sehari-hari, tetapi berbahaya untuk keputusan penting. Kita sering terlalu percaya diri pada kesimpulan yang dibuat dari data yang tidak mencukupi.', 3, false)
ON CONFLICT DO NOTHING;
